# Root scripts folder
# Example inside plugin folder: ./plugins/ScriptableMC/scripts
# Default: ./scripts
root_scripts_folder: './scripts'

# Prints some additional debugging messages
# Default: false
debug: false

# Version check on script engine start
# If enabled will make a request to the github api to check for updates
# and notify you if any updates are available
# Default: true
version_check: true

# Automatically extract js libraries to scripts lib folder if lib folder is missing
# If you set this to false you'll need to download and extract the libs manually.
# Default: true
extract_libs: true

common_js:
  # Enable CommonJS `require()` support
  # Allows the use of CommonJS NPM modules
  # Default: true
  enabled: true

  # CommonJS modules path
  # The default path to load CommonJS modules from.
  # Default: ${root_scripts_folder}/node_modules
  modules_path: '${root_scripts_folder}/node_modules'

  # CommonJS globals path
  # The path to the CommonJS globals.js file used to define global CommonJS values
  # Default: ${common_js.modules_path}/__globals__.js
  globals_path: '${common_js.modules_path}/__globals__.js'

# Chrome debugger settings
# **WARNING** THE DEBUGGER SHOULD NEVER BE ENABLED ON A PUBLIC SERVER
# IT IS INTENDED ONLY FOR DEBUGGING THE SCRIPT ENGINE AND CAN BREAK/FREEZE YOUR WHOLE SERVER
# Default: enabled: false, address: 127.0.0.1:9229, wait_attached: true
# If enabled: true and wait_attached: true the whole minecraft server will freeze until the chrome debugger is attached
# this is useful for debugging the script engine startup
# To enable remote debugging set address: 0.0.0.0:9229
debugger:
  enabled: '${debug}'
  address: 127.0.0.1:9229
  wait_attached: true