# Root scripts folder
# Example inside plugin folder: ./plugins/ScriptableMC/scripts
# Default: ./scripts
root_scripts_folder: './scripts'

# Prints some additional debugging messages
# Default: false
debug: false

# Version check on script engine start
# If enabled will make a request to the github api to check for updates
# and notify you if any updates are available
# Default: true
version_check: true

# Automatically extract js libraries to scripts lib-py folder if lib-py folder is missing
# If you set this to false you'll need to download and extract the python libs manually.
# Default: true
extract_libs: true

# Chrome debugger settings
# Default: enabled: false, address: 127.0.0.1:9229, wait_attached: true
# If enabled: true and wait_attached: true the whole minecraft server will hang until chrome debugger is attached
# this is useful for debugging the script engine on startup
# To enable remote debugging set address: 0.0.0.0:9229
debugger:
  enabled: false
  address: 127.0.0.1:9229
  wait_attached: true