name: ScriptableMC
description: 'Run JavaScript/TypeScript plugins for Bukkit/Spigot/Paper Minecraft 1.15'
version: '1.1.3'
api-version: '1.15'
author: AStorks
main: com.pixlfox.scriptablemc.ScriptablePluginMain
depend: [CommandAPI]
softdepend: [PlaceholderAPI]