name: Build Dev
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up Node.js 12.14.1
      uses: actions/setup-node@v1
      with:
        node-version: 12.14.1
    - name: Fix gradlew permissions
      run: chmod +x ./gradlew
    - name: Export TypeScript Libraries with Gradle
      run: ./gradlew --no-daemon exportTypeScriptLibraries
    - name: Compile TypeScript libraries and create archives
      run: |
        cd ./lib/
        npm install
        npm run compile
        cd ./ts/
        zip -r ../ScriptableMC-TypeScript-Lib.zip ./*
        cd ../js/
        zip -r ../ScriptableMC-JavaScript-Lib.zip ./*
        cd ../../
        cp ./lib/ScriptableMC-JavaScript-Lib.zip ./src/main/resources/libraries.zip
    - name: Build with Gradle
      run: ./gradlew --no-daemon shadowJar
    - name: Copy artifacts
      run: |
        mkdir artifacts
        cp ./build/libs/ScriptableMC.jar ./artifacts/
        cp ./lib/ScriptableMC-TypeScript-Lib.zip ./artifacts/
        cp ./lib/ScriptableMC-JavaScript-Lib.zip ./artifacts/
    - uses: actions/upload-artifact@v1
      with:
        name: ScriptableMC-DEV
        path: artifacts/
