name: Build
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up Node.js 12.14.1
      uses: actions/setup-node@v1
      with:
        node-version: 12.14.1
    - name: Fix gradlew permissions
      run: chmod +x ./gradlew
    - name: Export TypeScript Libraries with Gradle
      run: ./gradlew exportTypeScriptLibraries
    - name: Compile TypeScript libraries and create archives
      run: |
        cd ./lib/
        npm install
        npm run compile
        cd ./ts/
        zip -r ../ScriptableMC-TypeScript-Lib.zip ./*
        cd ../js/
        zip -r ../ScriptableMC-JavaScript-Lib.zip ./*
        cd ../../
        cp ./lib/ScriptableMC-JavaScript-Lib.zip ./src/main/resources/libraries.zip
    - name: Build with Gradle
      run: ./gradlew shadowJar
    - uses: actions/upload-artifact@v1
      with:
        name: ScriptableMC.jar
        path: build/libs/ScriptableMC.jar
    - uses: actions/upload-artifact@v1
      with:
        name: ScriptableMC-TypeScript-Lib.zip
        path: lib/ScriptableMC-TypeScript-Lib.zip
    - uses: actions/upload-artifact@v1
      with:
        name: ScriptableMC-JavaScript-Lib.zip
        path: lib/ScriptableMC-JavaScript-Lib.zip
