name: Java CI
on:
  push:
    tags:
    - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Fix gradlew permissions
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew shadowJar
    - name: Export TypeScript Libraries with Gradle
      run: ./gradlew exportTypeScriptLibraries
    - name: Compress TypeScript Libraries with Gradle
      run: zip -r ./lib/ScriptableMC-TypeScript-Lib.zip ./lib/ts/*
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: true
    - name: Upload Plugin Jar
      id: upload-plugin-jar
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./build/libs/ScriptableMC.jar
        asset_name: ScriptableMC.jar
        asset_content_type: application/java-archive
    - name: Upload TypeScript Libraries
      id: upload-typescript-libraries
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
        asset_path: ./lib/ScriptableMC-TypeScript-Lib.zip
        asset_name: ScriptableMC-TypeScript-Lib.zip
        asset_content_type: application/java-archive
