name: Build and Upload Release Artifacts
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up Node.js 12.14.1
      uses: actions/setup-node@v1
      with:
        node-version: 12.14.1
    - name: Fix gradlew permissions
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew shadowJar
    - name: Export TypeScript Libraries with Gradle
      run: ./gradlew exportTypeScriptLibraries
    - name: Compile TypeScript libraries and create archives for release
      run: |
        cd ./lib/
        npm install
        npm run compile
        cd ./ts/
        zip -r ../ScriptableMC-TypeScript-Lib.zip ./*
        cd ../js/
        zip -r ../ScriptableMC-JavaScript-Lib.zip ./*
    - name: Upload Plugin Jar
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'build/libs/ScriptableMC.jar'
    - name: Upload TypeScript Libraries
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'lib/ScriptableMC-TypeScript-Lib.zip'
    - name: Upload JavaScript Libraries
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'lib/ScriptableMC-JavaScript-Lib.zip'
